# -*- coding: utf-8 -*-
"""Quadrant_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19iC3IJ9mI8BLzIrOKUGsTpl2hA4Tfo12
"""

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# ─────────────────────────────────────────────
# LOAD DATA
# ─────────────────────────────────────────────
df = pd.read_excel("data.xlsx")

# ─────────────────────────────────────────────
# COLUMN VALIDATION
# ─────────────────────────────────────────────
required = ['numVotes', 'averageRating', 'runTime',
            'combined', 'MPAA_Rating', 'Genre',
            'performance', 'distributor']

missing = [c for c in required if c not in df.columns]
if missing:
    raise ValueError(f"Missing columns in dataset: {missing}")

print("Dataset loaded successfully.")
print(f"Total records: {len(df)}")
print(f"Performance values found: {df['performance'].unique()}\n")

# ─────────────────────────────────────────────
# HELPER: MPAA AND GENRE MULTIPLIERS
# ─────────────────────────────────────────────
def mpaa_multiplier(val):
    return 1.1 if str(val).strip() in ['PG-13', 'R'] else 1.0

def genre_commitment_mult(val):
    commit_genres = ['Action', 'Adventure', 'Animation']
    return 1.1 if any(g in str(val) for g in commit_genres) else 1.0

def genre_convenience_mult(val):
    conv_genres = ['Drama', 'Romance', 'Comedy']
    return 1.1 if any(g in str(val) for g in conv_genres) else 1.0

# ─────────────────────────────────────────────
# MAIN FUNCTION: CALCULATE INDICES + QUADRANT
# ─────────────────────────────────────────────
def run_model(df_in, normalisation='log', config=1):
    df = df_in.copy()

    df = df.dropna(subset=['numVotes', 'averageRating', 'runTime', 'combined'])
    df = df[df['numVotes'] > 0]
    df = df[df['runTime'] > 0]

    # Normalise numVotes
    max_votes = df['numVotes'].max()
    if normalisation == 'log':
        df['votes_norm'] = np.log10(df['numVotes']) / np.log10(max_votes)
    elif normalisation == 'linear':
        df['votes_norm'] = df['numVotes'] / max_votes
    elif normalisation == 'sqrt':
        df['votes_norm'] = np.sqrt(df['numVotes']) / np.sqrt(max_votes)

    df['runtime_norm'] = df['runTime'].apply(lambda x: min(x, 180) / 180)
    df['rating_norm']  = df['averageRating'] / 10

    df['primary_mult']      = df['combined'].apply(lambda x: 1.5 if str(x).strip().lower() == 'old' else 1.0)
    df['primary_mult_conv'] = df['combined'].apply(lambda x: 1.5 if str(x).strip().lower() == 'new' else 1.0)

    if config == 1:
        df['commitment_logic'] = (
            df['primary_mult'] * df['votes_norm'] * df['runtime_norm']
        )
        df['convenience_logic'] = (
            df['primary_mult_conv'] * df['rating_norm'] * (1 - df['runtime_norm'])
        )

    elif config == 2:
        df['commitment_logic'] = (
            df['primary_mult'] * df['votes_norm'] * df['rating_norm'] * df['runtime_norm']
        )
        df['convenience_logic'] = (
            df['primary_mult_conv'] * df['votes_norm'] * df['rating_norm'] * (1 - df['runtime_norm'])
        )

    elif config == 3:
        df['mpaa_mult']         = df['MPAA_Rating'].apply(mpaa_multiplier)
        df['genre_commit_mult'] = df['Genre'].apply(genre_commitment_mult)
        df['genre_conv_mult']   = df['Genre'].apply(genre_convenience_mult)

        df['commitment_logic'] = (
            df['primary_mult'] * df['votes_norm'] * df['rating_norm']
            * df['runtime_norm'] * df['mpaa_mult'] * df['genre_commit_mult']
        )
        df['convenience_logic'] = (
            df['primary_mult_conv'] * df['votes_norm'] * df['rating_norm']
            * (1 - df['runtime_norm']) * df['genre_conv_mult']
        )

    # Quadrant assignment using MEAN thresholds
    commit_mean = df['commitment_logic'].mean()
    conv_mean   = df['convenience_logic'].mean()

    def assign_quadrant(row):
        high_c  = row['commitment_logic']  >= commit_mean
        high_cv = row['convenience_logic'] >= conv_mean
        if high_c and high_cv:
            return 'Scenario 4: Hybrid Logic'
        elif high_c and not high_cv:
            return 'Scenario 1: Strong Commitment'
        elif not high_c and high_cv:
            return 'Scenario 3: Strong Convenience'
        else:
            return 'Scenario 2: Weak Commitment/Convenience'

    df['quadrant'] = df.apply(assign_quadrant, axis=1)

    return df, commit_mean, conv_mean


# ─────────────────────────────────────────────
# ACCURACY CALCULATION
# ─────────────────────────────────────────────
def calculate_accuracy(df):
    cinema    = df[df['performance'].isin(['cinema-hit', 'cinema-flop'])]
    streaming = df[df['performance'].isin(['Streaming-hit', 'Streaming-flop'])]

    cinema_hits_total    = len(cinema[cinema['performance'] == 'cinema-hit'])
    streaming_hits_total = len(streaming[streaming['performance'] == 'Streaming-hit'])

    cinema_correct = len(cinema[
        (cinema['performance'] == 'cinema-hit') &
        (cinema['quadrant'].isin(['Scenario 1: Strong Commitment',
                                   'Scenario 4: Hybrid Logic']))
    ])
    streaming_correct = len(streaming[
        (streaming['performance'] == 'Streaming-hit') &
        (streaming['quadrant'] == 'Scenario 3: Strong Convenience')
    ])

    cinema_acc    = (cinema_correct / cinema_hits_total * 100) if cinema_hits_total > 0 else 0
    streaming_acc = (streaming_correct / streaming_hits_total * 100) if streaming_hits_total > 0 else 0
    overall_acc   = (
        (cinema_correct + streaming_correct) /
        (cinema_hits_total + streaming_hits_total) * 100
    ) if (cinema_hits_total + streaming_hits_total) > 0 else 0

    return round(cinema_acc, 1), round(streaming_acc, 1), round(overall_acc, 1)


# ─────────────────────────────────────────────
# MISS ANALYSIS
# ─────────────────────────────────────────────
def calculate_misses(df):
    cinema    = df[df['performance'].isin(['cinema-hit', 'cinema-flop'])]
    streaming = df[df['performance'].isin(['Streaming-hit', 'Streaming-flop'])]

    cinema_hits_total     = len(cinema[cinema['performance'] == 'cinema-hit'])
    streaming_hits_total  = len(streaming[streaming['performance'] == 'Streaming-hit'])
    cinema_flops_total    = len(cinema[cinema['performance'] == 'cinema-flop'])
    streaming_flops_total = len(streaming[streaming['performance'] == 'Streaming-flop'])

    # Miss counts
    cinema_correct = len(cinema[
        (cinema['performance'] == 'cinema-hit') &
        (cinema['quadrant'].isin(['Scenario 1: Strong Commitment',
                                   'Scenario 4: Hybrid Logic']))])
    cinema_misses  = cinema_hits_total - cinema_correct

    streaming_correct = len(streaming[
        (streaming['performance'] == 'Streaming-hit') &
        (streaming['quadrant'] == 'Scenario 3: Strong Convenience')])
    streaming_misses  = streaming_hits_total - streaming_correct

    cinema_miss_rate    = round(cinema_misses    / cinema_hits_total    * 100, 1) if cinema_hits_total    > 0 else 0
    streaming_miss_rate = round(streaming_misses / streaming_hits_total * 100, 1) if streaming_hits_total > 0 else 0

    # False commitment: cinema-flops predicted as cinema-suitable
    false_commitment = len(cinema[
        (cinema['performance'] == 'cinema-flop') &
        (cinema['quadrant'].isin(['Scenario 1: Strong Commitment',
                                   'Scenario 4: Hybrid Logic']))])
    false_commitment_rate = round(false_commitment / cinema_flops_total * 100, 1) if cinema_flops_total > 0 else 0

    # False convenience: Streaming-flops predicted as streaming-suitable
    false_convenience = len(streaming[
        (streaming['performance'] == 'Streaming-flop') &
        (streaming['quadrant'] == 'Scenario 3: Strong Convenience')])
    false_convenience_rate = round(false_convenience / streaming_flops_total * 100, 1) if streaming_flops_total > 0 else 0

    # Severity: where did missed cinema-hits land?
    cinema_miss_in_s2 = len(cinema[
        (cinema['performance'] == 'cinema-hit') &
        (cinema['quadrant'] == 'Scenario 2: Weak Commitment/Convenience')])
    cinema_miss_in_s3 = len(cinema[
        (cinema['performance'] == 'cinema-hit') &
        (cinema['quadrant'] == 'Scenario 3: Strong Convenience')])

    # Severity: where did missed Streaming-hits land?
    streaming_miss_in_s1 = len(streaming[
        (streaming['performance'] == 'Streaming-hit') &
        (streaming['quadrant'] == 'Scenario 1: Strong Commitment')])
    streaming_miss_in_s2 = len(streaming[
        (streaming['performance'] == 'Streaming-hit') &
        (streaming['quadrant'] == 'Scenario 2: Weak Commitment/Convenience')])

    print(f"  Cinema miss rate:             {cinema_miss_rate}% ({cinema_misses} of {cinema_hits_total} cinema-hits misclassified)")
    print(f"    - Mild miss (Scenario 2):   {cinema_miss_in_s2} films (uncertain, not wrong platform)")
    print(f"    - Severe miss (Scenario 3): {cinema_miss_in_s3} films (predicted streaming for a cinema hit)")
    print(f"  Streaming miss rate:          {streaming_miss_rate}% ({streaming_misses} of {streaming_hits_total} Streaming-hits misclassified)")
    print(f"    - Severe miss (Scenario 1): {streaming_miss_in_s1} films (predicted cinema for a streaming hit)")
    print(f"    - Mild miss (Scenario 2):   {streaming_miss_in_s2} films (uncertain, not wrong platform)")
    print(f"  False commitment rate:        {false_commitment_rate}% ({false_commitment} of {cinema_flops_total} cinema-flops predicted as cinema-suitable)")
    print(f"  False convenience rate:       {false_convenience_rate}% ({false_convenience} of {streaming_flops_total} Streaming-flops predicted as streaming-suitable)")

    return {
        'Cinema miss rate (%)':         cinema_miss_rate,
        'Streaming miss rate (%)':      streaming_miss_rate,
        'False commitment rate (%)':    false_commitment_rate,
        'False convenience rate (%)':   false_convenience_rate,
        'Cinema severe misses (S3)':    cinema_miss_in_s3,
        'Cinema mild misses (S2)':      cinema_miss_in_s2,
        'Streaming severe misses (S1)': streaming_miss_in_s1,
        'Streaming mild misses (S2)':   streaming_miss_in_s2,
    }


# ─────────────────────────────────────────────
# RUN ALL 9 COMBINATIONS
# ─────────────────────────────────────────────
normalisations = ['log', 'linear', 'sqrt']
configs        = [1, 2, 3]
model_labels   = {
    ('log',    1): '1A', ('log',    2): '1B', ('log',    3): '1C',
    ('linear', 1): '2A', ('linear', 2): '2B', ('linear', 3): '2C',
    ('sqrt',   1): '3A', ('sqrt',   2): '3B', ('sqrt',   3): '3C',
}

summary_rows = []
all_results  = {}

print("=" * 70)
print("RUNNING ALL 9 MODEL CONFIGURATIONS")
print("=" * 70)

for norm in normalisations:
    for config in configs:
        label = model_labels[(norm, config)]

        df_result, commit_mean, conv_mean = run_model(df, norm, config)

        # Calculate accuracy — must come before calculate_misses print block
        cinema_acc, streaming_acc, overall_acc = calculate_accuracy(df_result)

        print(f"\nModel {label} | Normalisation: {norm} | Config: {config}")
        print(f"  Commitment mean: {commit_mean:.4f} | Convenience mean: {conv_mean:.4f}")
        print(f"  Cinema accuracy:    {cinema_acc}%")
        print(f"  Streaming accuracy: {streaming_acc}%")
        print(f"  Overall accuracy:   {overall_acc}%")

        # Calculate misses — called here so miss_data exists before summary_rows
        miss_data = calculate_misses(df_result)

        all_results[label] = df_result

        summary_rows.append({
            'Model':                        label,
            'Normalisation':                norm,
            'Config':                       config,
            'Commit mean threshold':        round(commit_mean, 4),
            'Conv mean threshold':          round(conv_mean,   4),
            'Cinema accuracy (%)':          cinema_acc,
            'Streaming accuracy (%)':       streaming_acc,
            'Overall accuracy (%)':         overall_acc,
            'Cinema miss rate (%)':         miss_data['Cinema miss rate (%)'],
            'Streaming miss rate (%)':      miss_data['Streaming miss rate (%)'],
            'False commitment rate (%)':    miss_data['False commitment rate (%)'],
            'False convenience rate (%)':   miss_data['False convenience rate (%)'],
            'Cinema severe misses (S3)':    miss_data['Cinema severe misses (S3)'],
            'Cinema mild misses (S2)':      miss_data['Cinema mild misses (S2)'],
            'Streaming severe misses (S1)': miss_data['Streaming severe misses (S1)'],
            'Streaming mild misses (S2)':   miss_data['Streaming mild misses (S2)'],
        })

        # Cinema crosstab
        cinema_df = df_result[df_result['performance'].isin(['cinema-hit', 'cinema-flop'])]
        if len(cinema_df) > 0:
            cinema_cross = pd.crosstab(cinema_df['quadrant'], cinema_df['performance'])
            print("\n  Cinema breakdown:")
            print(cinema_cross.to_string())

        # Streaming crosstab
        streaming_df = df_result[df_result['performance'].isin(['Streaming-hit', 'Streaming-flop'])]
        if len(streaming_df) > 0:
            streaming_cross = pd.crosstab(streaming_df['quadrant'], streaming_df['performance'])
            print("\n  Streaming breakdown:")
            print(streaming_cross.to_string())
        else:
            print("\n  Streaming breakdown: No streaming rows found.")

        print("-" * 70)


# ─────────────────────────────────────────────
# SUMMARY TABLE
# ─────────────────────────────────────────────
summary_df = pd.DataFrame(summary_rows)
print("\n")
print("=" * 70)
print("SUMMARY: ALL 9 MODELS")
print("=" * 70)
print(summary_df.to_string(index=False))

# ─────────────────────────────────────────────
# IDENTIFY BEST MODEL
# ─────────────────────────────────────────────
best_cinema    = summary_df.loc[summary_df['Cinema accuracy (%)'].idxmax()]
best_streaming = summary_df.loc[summary_df['Streaming accuracy (%)'].idxmax()]
best_overall   = summary_df.loc[summary_df['Overall accuracy (%)'].idxmax()]

print(f"\nBest cinema accuracy:    Model {best_cinema['Model']} ({best_cinema['Cinema accuracy (%)']}%)")
print(f"Best streaming accuracy: Model {best_streaming['Model']} ({best_streaming['Streaming accuracy (%)']}%)")
print(f"Best overall accuracy:   Model {best_overall['Model']} ({best_overall['Overall accuracy (%)']}%)")

# ─────────────────────────────────────────────
# EXPORT RESULTS TO EXCEL
# ─────────────────────────────────────────────
output_path = "model_results.xlsx"
with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
    summary_df.to_excel(writer, sheet_name='Summary', index=False)
    for label, df_result in all_results.items():
        cols_to_export = ['Title', 'distributor', 'performance', 'combined',
                          'averageRating', 'numVotes', 'runTime',
                          'commitment_logic', 'convenience_logic', 'quadrant']
        cols_available = [c for c in cols_to_export if c in df_result.columns]
        df_result[cols_available].to_excel(
            writer, sheet_name=f'Model_{label}', index=False)

print(f"\nResults exported to: {output_path}")
print("Each model has its own sheet. Summary sheet contains accuracy comparison.")

