# -*- coding: utf-8 -*-
"""mpaa_ratings_franchise_netflix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aUp8PDxIukMWzDHZel8OOKUDVTKD37M3
"""

import pandas as pd

data = pd.read_csv('netflix.csv')

data.info()

import requests
import pandas as pd
import time

API_KEY = 'aea4facd354ec9322145af2d4b3238c5'
# FIX 1: Added /3 to the end of the URL
BASE_URL = "https://api.themoviedb.org/3"

def get_tmdb_insights(df_input):
    results = []

    # Trigger words for originality logic
    sequel_terms = ['sequel', 'part ii', 'part 2', 'chapter 2', 'return of', 'vol. 2', 'volume 2']
    remake_terms = ['remake', 'reimagining', 'reboot', 'based on the original']
    adaptation_terms = ['based on the novel', 'based on the book', 'based on the comic',
                        'based on the true story', 'adapted from', 'graphic novel', 'adaptation']

    for index, row in df_input.iterrows():
        imdb_id = row['tconst']
        current_result = {'tconst': imdb_id, 'MPAA_Rating': None, 'is_sequel': 0, 'is_franchise': 0, 'is_adaptation': 0, 'is_remake': 0, 'budget': 0, 'revenue': 0}

        # 1. Use 'find' to link IMDb ID to TMDB ID
        find_url = f"{BASE_URL}/find/{imdb_id}?api_key={API_KEY}&external_source=imdb_id"

        try:
            response = requests.get(find_url)

            # FIX 2: Check if the response is actually valid before calling .json()
            if response.status_code != 200:
                print(f"Error {response.status_code} for {row['Title']}. Waiting...")
                time.sleep(2) # Wait a bit if server is busy
                continue

            find_res = response.json()
            movie_results = find_res.get('movie_results', [])

            if not movie_results:
                results.append(current_result)
                continue

            tmdb_id = movie_results[0]['id']

            # 2. Get Details, Keywords, and Release Dates
            details_url = f"{BASE_URL}/movie/{tmdb_id}?api_key={API_KEY}&append_to_response=keywords,release_dates"
            m = requests.get(details_url).json()

            # 3. Extract US MPAA Rating
            mpaa = "Not Rated"
            for country in m.get('release_dates', {}).get('results', []):
                if country['iso_3166_1'] == 'US':
                    for release in country['release_dates']:
                        if release.get('certification'):
                            mpaa = release['certification']
                            break

            # 4. Feature Engineering: Originality Logic (FIXED)
            overview = str(m.get('overview', '')).lower()
            tagline = str(m.get('tagline', '')).lower()
            keywords = " ".join([k['name'].lower() for k in m.get('keywords', {}).get('keywords', [])])
            title_text = str(m.get('title', '')).lower()
            text = f"{overview} {tagline} {keywords}"

            # Make sure 'w' is used consistently in all three lines below:
            is_remake = 1 if any(w in text for w in remake_terms) else 0
            is_adaptation = 1 if any(w in text for w in adaptation_terms) else 0
            is_sequel = 1 if any(w in title_text for w in sequel_terms) or 'sequel' in text else 0
            is_franchise = 1 if (is_sequel == 1 or is_remake == 1) else 0


            current_result.update({
                'MPAA_Rating': mpaa, 'is_sequel': is_sequel, 'is_franchise': is_franchise,
                'is_adaptation': is_adaptation, 'is_remake': is_remake,
                'budget': m.get('budget', 0), 'revenue': m.get('revenue', 0)
            })
            print(f"Matched: {row['Title']} -> {mpaa}")

        except Exception as e:
            print(f"Skipping {row['Title']} due to error: {e}")

        results.append(current_result)
        # FIX 3: Increased sleep slightly to be safe with rate limits
        time.sleep(0.2)

    df_tmdb = pd.DataFrame(results)
    # drop_duplicates prevents the final data from becoming massive if code is run twice
    df_tmdb = df_tmdb.drop_duplicates(subset=['tconst'])
    return pd.merge(df_input, df_tmdb, on='tconst', how='left')

# RUN THE CODE
data = get_tmdb_insights(data)

data.info()

data['MPAA_Rating'] = data['MPAA_Rating'].fillna('NA')

data.to_csv('netflix_movies.csv')

