# -*- coding: utf-8 -*-
"""netflix_imdb_tmdb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AlIsUuNBBAohvY8yD-BJPvYW1y0HUSqA

This script was generated with AI assistance (Claude, Anthropic) to handle the TMDb API calls and IMDb merging for the streaming dataset.

The data collection logic and classification decisions are mine.
"""

import pandas as pd
import numpy as np
import requests
import time

# load the netflix list scraped from wikipedia
df_netflix = pd.read_excel('netflix_clean.xlsx')
df_netflix['runTime'] = pd.to_numeric(df_netflix['runTime'], errors='coerce')

print(f"Netflix records: {len(df_netflix)}")
print(df_netflix.info())


API_KEY  = 'your_api_key_here'
BASE_URL = "https://api.themoviedb.org/3"

# words used to identify sequels, remakes and adaptations from TMDb text fields
sequel_terms     = ['sequel', 'part ii', 'part 2', 'chapter 2', 'return of', 'vol. 2']
remake_terms     = ['remake', 'reimagining', 'reboot', 'based on the original']
adaptation_terms = ['based on the novel', 'based on the book', 'based on the comic',
                    'based on the true story', 'adapted from', 'graphic novel']


def get_tmdb_data(df_input):
    results = []

    for _, row in df_input.iterrows():
        title  = str(row['Title']).strip()
        year   = str(row['Release date'])[:4]

        # default values in case no match is found
        entry = {
            'Title':        title,
            'tconst':       None,
            'MPAA_Rating':  'NR',
            'is_franchise': 'Non-franchise',
            'is_original':  'Original'
        }

        try:
            # search TMDb by title and release year
            search = requests.get(f"{BASE_URL}/search/movie",
                                  params={'api_key': API_KEY, 'query': title, 'year': year})
            movies = search.json().get('results', [])

            if not movies:
                results.append(entry)
                time.sleep(0.3)
                continue

            # get full movie details including keywords and release dates
            tmdb_id  = movies[0]['id']
            details  = requests.get(f"{BASE_URL}/movie/{tmdb_id}",
                                    params={'api_key': API_KEY,
                                            'append_to_response': 'keywords,release_dates'}).json()

            # grab the IMDb ID (tconst) for the IMDb merge later
            entry['tconst'] = details.get('imdb_id')

            # get US content rating
            for country in details.get('release_dates', {}).get('results', []):
                if country['iso_3166_1'] == 'US':
                    for release in country['release_dates']:
                        if release.get('certification'):
                            entry['MPAA_Rating'] = release['certification']
                            break

            # build a text blob from overview, tagline and keywords to check originality
            overview = str(details.get('overview', '')).lower()
            tagline  = str(details.get('tagline',  '')).lower()
            keywords = ' '.join([k['name'].lower() for k in
                                 details.get('keywords', {}).get('keywords', [])])
            text      = f"{overview} {tagline} {keywords}"
            title_lower = str(details.get('title', '')).lower()

            is_sequel     = any(w in title_lower or w in text for w in sequel_terms)
            is_remake     = any(w in text for w in remake_terms)
            is_adaptation = any(w in text for w in adaptation_terms)
            in_collection = details.get('belongs_to_collection') is not None

            if is_sequel or in_collection:
                entry['is_franchise'] = 'Franchise'
            if is_sequel or is_remake or is_adaptation:
                entry['is_original'] = 'Non-Original'

            print(f"Matched: {title} | {entry['MPAA_Rating']} | {entry['is_franchise']} | {entry['is_original']}")

        except Exception as e:
            print(f"Skipping {title}: {e}")

        results.append(entry)
        time.sleep(0.3)

    tmdb_df = pd.DataFrame(results).drop_duplicates(subset=['Title'])
    return df_input.merge(tmdb_df, on='Title', how='left')


df_netflix = get_tmdb_data(df_netflix)
print(f"\nAfter TMDb merge: {len(df_netflix)} records")
print(df_netflix[['is_franchise', 'is_original']].value_counts())


# merge with IMDb using tconst to get averageRating and numVotes
ratings = pd.read_csv('title.ratings.tsv', sep='\t')
basics  = pd.read_csv('title.basics.tsv',  sep='\t',
                       usecols=['tconst', 'runtimeMinutes', 'genres'])

before = len(df_netflix)
df_netflix = df_netflix.merge(ratings, on='tconst', how='left')
df_netflix = df_netflix.merge(basics,  on='tconst', how='left')
df_netflix = df_netflix.rename(columns={'genres': 'Genre'})

df_netflix['averageRating'] = pd.to_numeric(df_netflix['averageRating'], errors='coerce')
df_netflix['numVotes']      = pd.to_numeric(df_netflix['numVotes'],      errors='coerce')
df_netflix = df_netflix.dropna(subset=['averageRating', 'numVotes'])

print(f"\nAfter IMDb merge: {len(df_netflix)} records, lost {before - len(df_netflix)}")


# load netflix top 10 weekly data and count appearances per title
top10 = pd.read_excel('all-weeks-global.xlsx')

weeks = (top10.groupby('show_title')['cumulative_weeks_in_top_10']
              .max()
              .reset_index()
              .rename(columns={'show_title': 'Title',
                               'cumulative_weeks_in_top_10': 'total_weeks'}))

df_netflix = df_netflix.merge(weeks, on='Title', how='left')
df_netflix['total_weeks'] = df_netflix['total_weeks'].fillna(0)

# classify as hit or flop
# appearing at least once in the top 10 from hundreds of simultaneous
# releases is used as the threshold given how competitive the platform is
df_netflix['performance'] = df_netflix['total_weeks'].apply(
    lambda x: 'Streaming-hit' if x > 2 else 'Streaming-flop')

df_netflix['distributor'] = 'streaming'

print(f"\nFinal dataset: {len(df_netflix)} records")
print(df_netflix['performance'].value_counts())

df_netflix.to_excel('streaming_final.xlsx', index=False)
print("Saved to streaming_final.xlsx")



