# -*- coding: utf-8 -*-
"""cinema_streaming_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uYmVhs9EPgVtpu18GMwUwzH63YndV3JZ
"""

#load the necessary libraries
import pandas as pd
import numpy as np

#for classifying
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import f1_score, balanced_accuracy_score, classification_report

from imblearn.over_sampling import SMOTE

#for categorizing text
from sklearn.preprocessing import LabelEncoder

#for one hot encoding
from sklearn.preprocessing import MultiLabelBinarizer


import seaborn as sns
import matplotlib.pyplot as plt

#load the dataset
data = pd.read_excel('movies_visuals.xlsx')
data.info()

"""**Feature Importance for Streaming Data**"""

#Converting text columns to numbers (Encoding)
le = LabelEncoder()
data['MPAA_Rating'] = le.fit_transform(data['MPAA_Rating'].astype(str))
data['Season'] = le.fit_transform(data['Season'].astype(str))
data['Original'] = le.fit_transform(data['Original'].astype(str))
data['Franchise'] = le.fit_transform(data['Franchise'].astype(str))

#Flattening genres into a list of single words
#Instead of "Action, Sci-Fi", it becomes ["Action", "Sci-Fi"]
data['genres_split'] = data['Genre'].str.split(',')

#Using MultiLabelBinarizer to create clean, single-genre columns
mlb = MultiLabelBinarizer()
genre_dummies = pd.DataFrame(mlb.fit_transform(data['genres_split']),
                             columns=mlb.classes_,
                             index=data.index)

#Joining these clean columns back to your main dataframe
df_final = pd.concat([data, genre_dummies], axis=1)

#only 'streaming' values
df = df_final[df_final['distributor'] == 'streaming']

#base features
base_feature = df[['runTime', 'averageRating', 'numVotes', 'MPAA_Rating', 'Original', 'Season', 'Franchise']]

#genre features
genre_columns = list(mlb.classes_)

#final features
X = df[base_feature.columns.tolist() + genre_columns]

#target
y = df['performance']

#Spliting into Training (80%) and Testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#training the data
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')


#Now training on the resampled data
rf_model.fit(X_train, y_train)

#obtaining feature importance
importances = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf_model.feature_importances_
}).sort_values(by='Importance', ascending=False)

print("--- Feature Importance ---")
print(importances.head(10))

"""**Feature Importance for cinema releases**"""

#only 'streaming' values
df = df_final[df_final['distributor'] == 'cinema']

#base features
base_feature = df[['runTime', 'averageRating', 'numVotes', 'MPAA_Rating', 'Original', 'Season', 'Franchise']]

#genre features
genre_columns = list(mlb.classes_)

#final features
X = df[base_feature.columns.tolist() + genre_columns]

#target
y = df['performance']

#Spliting into Training (80%) and Testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#training the data
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')


#Now training on the resampled data
rf_model.fit(X_train, y_train)

#obtaining feature importance
importances = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf_model.feature_importances_
}).sort_values(by='Importance', ascending=False)

print("--- Feature Importance ---")
print(importances.head(10))