# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I4VyAQ399puOoHmKDvBjHL3moHOaaDXB

**Load the necessary libraries**
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# ---------------------------------------------------------
# 1. PAGE SETUP
# ---------------------------------------------------------
st.set_page_config(page_title="Movie Strategic Quadrant Predictor", layout="wide")
st.title("🎬 Movie Strategy & Performance Analyzer")
st.markdown("Enter movie details to see where it falls in the **Hadida Strategic Quadrants**.")

# ---------------------------------------------------------
# 2. SIDEBAR INPUTS
# ---------------------------------------------------------
st.sidebar.header("Movie Metadata")

title = st.sidebar.text_input("Movie Title", "New Movie")
distributor = st.sidebar.selectbox("Distributor", ["cinema", "streaming"])
runtime = st.sidebar.number_input("Run Time (minutes)", min_value=1, value=100)
genre = st.sidebar.text_input("Genre (e.g., Action, Drama)", "Drama")
mpaa = st.sidebar.selectbox("MPAA Rating", ["G", "PG", "PG-13", "R", "Not Rated"])
is_original = st.sidebar.toggle("Is Original?", value=True)
is_franchise = st.sidebar.toggle("Is Franchise?", value=False)
avg_rating = st.sidebar.slider("Average Rating (IMDb Proxy)", 1.0, 10.0, 6.5)
num_votes = st.sidebar.number_input("Num Votes (Popularity Proxy)", min_value=0, value=1000)

# ---------------------------------------------------------
# 3. BACKGROUND CALCULATIONS
# ---------------------------------------------------------

# Normalization constants (from dataset assumptions)
MAX_VOTES = 1_500_000
MAX_RUNTIME = 250

# Determine logic type
combined = "new" if is_original and not is_franchise else "old"

# Commitment Logic
commitment_weight = 1.8 if combined == "old" else 0.8
commitment_score = commitment_weight * (num_votes / MAX_VOTES) * (runtime / MAX_RUNTIME)

# Convenience Logic
convenience_weight = 1.8 if combined == "new" else 0.8
convenience_score = convenience_weight * (avg_rating / 10) * (1 - (runtime / MAX_RUNTIME))

# Determine Quadrant
if commitment_score >= 0.03 and convenience_score >= 0.5:
    quadrant = "Scenario 4: Hybrid Logic"
elif commitment_score >= 0.03 and convenience_score < 0.5:
    quadrant = "Scenario 1: Strong Commitment"
elif commitment_score < 0.03 and convenience_score >= 0.5:
    quadrant = "Scenario 3: Strong Convenience"
else:
    quadrant = "Scenario 2: Weak Commitment/Convenience"

# ---------------------------------------------------------
# 4. DISPLAY RESULTS
# ---------------------------------------------------------
col1, col2 = st.columns([1, 2])

with col1:
    st.subheader("Analysis Results")
    st.metric("Strategic Quadrant", quadrant)
    st.write(f"**Commitment Score:** {commitment_score:.4f}")
    st.write(f"**Convenience Score:** {convenience_score:.4f}")
    st.write(f"**Logic Type:** {combined.capitalize()}")

with col2:
    # Data for scatter plot
    plot_data = pd.DataFrame({
        'Commitment': [commitment_score],
        'Convenience': [convenience_score],
        'Title': [title],
        'Quadrant': [quadrant]
    })

    fig = px.scatter(
        plot_data,
        x='Commitment',
        y='Convenience',
        text='Title',
        range_x=[0, 0.2],
        range_y=[0, 2.0],
        title="Hadida Strategic Mapping"
    )

    # Quadrant boundaries
    fig.add_vline(x=0.03, line_dash="dash", line_color="gray")
    fig.add_hline(y=0.5, line_dash="dash", line_color="gray")

    st.plotly_chart(fig, use_container_width=True)

st.success(f"Successfully categorized '{title}' into **{quadrant}**!")