# -*- coding: utf-8 -*-
"""feature_importance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uYmVhs9EPgVtpu18GMwUwzH63YndV3JZ

The use of AI to debug and assist

The data collection logic and classification decisions are mine.
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, MultiLabelBinarizer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_excel('visuals.xlsx')
print(f"Total records loaded: {len(df)}")
print(f"Columns: {list(df.columns)}\n")


def prepare_features(data):
    data = data.copy()
    le = LabelEncoder()

    # encode categorical columns
    for col in ['MPAA_Rating', 'Season', 'is_original', 'is_franchise', 'combined']:
        if col in data.columns:
            data[col] = le.fit_transform(data[col].astype(str))
        else:
            print(f"Warning: column '{col}' not found, skipping")

    data['runTime'] = pd.to_numeric(data['runTime'], errors='coerce')

    # split genres into individual columns
    data['genres_split'] = data['Genre'].str.split(',').apply(
        lambda x: [g.strip() for g in x] if isinstance(x, list) else [])

    mlb = MultiLabelBinarizer()
    genre_dummies = pd.DataFrame(
        mlb.fit_transform(data['genres_split']),
        columns=mlb.classes_,
        index=data.index
    )

    df_final = pd.concat([data, genre_dummies], axis=1)
    df_final = df_final.dropna(subset=['runTime'])

    base_cols = ['runTime', 'averageRating', 'numVotes',
                 'MPAA_Rating', 'Season', 'is_original', 'is_franchise', 'combined']
    base_cols = [c for c in base_cols if c in df_final.columns]

    X = df_final[base_cols + list(mlb.classes_)]
    y = df_final['performance']
    X, y = X.align(y, join='inner', axis=0)
    return X, y, mlb, df_final


def evaluate_model(X, y, hit_label, flop_label, label):
    print(f"\n{label}")
    print("=" * 50)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42)

    model = RandomForestClassifier(
        n_estimators=100, random_state=42, class_weight='balanced')
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    overall_acc   = accuracy_score(y_test, y_pred)
    total_hits    = (y_test == hit_label).sum()
    total_flops   = (y_test == flop_label).sum()
    correct_hits  = ((y_test == hit_label)  & (y_pred == hit_label)).sum()
    correct_flops = ((y_test == flop_label) & (y_pred == flop_label)).sum()
    missed_hits   = ((y_test == hit_label)  & (y_pred == flop_label)).sum()
    missed_flops  = ((y_test == flop_label) & (y_pred == hit_label)).sum()

    hit_accuracy    = (correct_hits  / total_hits  * 100) if total_hits  > 0 else 0
    flop_accuracy   = (correct_flops / total_flops * 100) if total_flops > 0 else 0
    false_hit_rate  = (missed_flops  / total_flops * 100) if total_flops > 0 else 0
    false_flop_rate = (missed_hits   / total_hits  * 100) if total_hits  > 0 else 0

    print(f"\nTest set: {len(y_test)} films ({total_hits} hits, {total_flops} flops)")
    print(f"Overall accuracy: {overall_acc*100:.1f}%")

    print(f"\nHit analysis:")
    print(f"  Correctly predicted: {correct_hits} ({hit_accuracy:.1f}%)")
    print(f"  Missed (predicted as flop): {missed_hits} ({false_flop_rate:.1f}%)")

    print(f"\nFlop analysis:")
    print(f"  Correctly predicted: {correct_flops} ({flop_accuracy:.1f}%)")
    print(f"  Missed (predicted as hit): {missed_flops} ({false_hit_rate:.1f}%)")

    print(f"\nConfusion matrix:")
    cm = confusion_matrix(y_test, y_pred, labels=[hit_label, flop_label])
    cm_df = pd.DataFrame(cm,
                         index=[f"Actual {hit_label}", f"Actual {flop_label}"],
                         columns=[f"Predicted {hit_label}", f"Predicted {flop_label}"])
    print(cm_df.to_string())

    print(f"\nClassification report:")
    print(classification_report(y_test, y_pred))

    importances = pd.DataFrame({
        'Feature':    X.columns,
        'Importance': model.feature_importances_
    }).sort_values(by='Importance', ascending=False)

    print(f"\nFeature importance (top 10):")
    print(importances.head(10).to_string(index=False))

    return model, {
        'label':           label,
        'overall_acc':     round(overall_acc * 100, 1),
        'hit_accuracy':    round(hit_accuracy, 1),
        'flop_accuracy':   round(flop_accuracy, 1),
        'correct_hits':    int(correct_hits),
        'missed_hits':     int(missed_hits),
        'correct_flops':   int(correct_flops),
        'missed_flops':    int(missed_flops),
        'false_hit_rate':  round(false_hit_rate, 1),
        'false_flop_rate': round(false_flop_rate, 1),
        'total_hits':      int(total_hits),
        'total_flops':     int(total_flops),
    }, importances


# run cinema
cinema_data = df[df['distributor'] == 'cinema'].copy()
print(f"Cinema records: {len(cinema_data)}")
X_c, y_c, mlb_c, df_c = prepare_features(cinema_data)
cinema_model, cinema_stats, cinema_imp = evaluate_model(
    X_c, y_c, 'cinema-hit', 'cinema-flop', 'CINEMA MODEL')


# run streaming
stream_data = df[df['distributor'] == 'streaming'].copy()
print(f"\nStreaming records: {len(stream_data)}")
X_s, y_s, mlb_s, df_s = prepare_features(stream_data)
stream_model, stream_stats, stream_imp = evaluate_model(
    X_s, y_s, 'Streaming-hit', 'Streaming-flop', 'STREAMING MODEL')


# side by side comparison
print(f"\nSIDE BY SIDE COMPARISON")
print("=" * 50)
print(f"\n{'Metric':<35} {'Cinema':>10} {'Streaming':>12}")
print("-" * 57)
print(f"{'Overall accuracy':<35} {cinema_stats['overall_acc']:>9}% {stream_stats['overall_acc']:>11}%")
print(f"{'Hit accuracy':<35} {cinema_stats['hit_accuracy']:>9}% {stream_stats['hit_accuracy']:>11}%")
print(f"{'Flop accuracy':<35} {cinema_stats['flop_accuracy']:>9}% {stream_stats['flop_accuracy']:>11}%")
print(f"{'Hits correctly predicted':<35} {cinema_stats['correct_hits']:>9} {stream_stats['correct_hits']:>11}")
print(f"{'Hits missed (predicted as flop)':<35} {cinema_stats['missed_hits']:>9} {stream_stats['missed_hits']:>11}")
print(f"{'Flops correctly predicted':<35} {cinema_stats['correct_flops']:>9} {stream_stats['correct_flops']:>11}")
print(f"{'Flops missed (predicted as hit)':<35} {cinema_stats['missed_flops']:>9} {stream_stats['missed_flops']:>11}")
print(f"{'False hit rate':<35} {cinema_stats['false_hit_rate']:>9}% {stream_stats['false_hit_rate']:>11}%")
print(f"{'Miss rate (hits predicted wrong)':<35} {cinema_stats['false_flop_rate']:>9}% {stream_stats['false_flop_rate']:>11}%")


# export results
summary = pd.DataFrame([cinema_stats, stream_stats])
with pd.ExcelWriter("model_evaluation.xlsx", engine='openpyxl') as writer:
    summary.to_excel(writer, sheet_name='Summary', index=False)
    cinema_imp.to_excel(writer, sheet_name='Cinema Feature Importance', index=False)
    stream_imp.to_excel(writer, sheet_name='Streaming Feature Importance', index=False)

print(f"\nResults exported to model_evaluation.xlsx")

